# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
# Source: https://github.com/hk2012/hongkuan.github.io.git

# Site
title: 流年印记
subtitle: 总结过去 领悟现在 洞悉未来
description: 数学 & 软件工程
keywords: 博客,笔记,生活
author: 洪宽
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://hongkuan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  # enable: true
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  教程: course
  博客: blog
  文档: doc
  笔记: note
  JAVA: java
  数学: math
  其他: other
categories:
- [文档, 笔记, 编程, 数学]
tag_map:


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: land
theme: shoka

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  # repo: https://github.com/hk2012/hk2012.github.io.git

  repo: git@github.com:hk2012/hongkuan.github.io.git
  
  branch: master
vendors:
  css:
    # 略略略
  js:
    # 略略略
    
# 自动生成sitemap
sitemap:
	path: sitemap.xml
baidusitemap: 
  path: baidusitemap.xml

# 全文搜索
algolia:
  appId: P4YJLTPN69
  apiKey: 7f3b5c20d0eec5b5c0443eb1407ba2ff
  adminApiKey: f5846f8d737e90ff125d14fdd81817bf
  chunkSize: 5000
  indexName: "hongkuan"
  fields:
    - title 
    - path 
    - categories 
    - content:strip:truncate,0,4000
    - gallery
    - photos
    - tags
markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer: 
    quotes: '“”‘’'
  plugins: # markdown-it插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的class名称，shoka主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"
minify:
  html:
    enable: true
    exclude: # 排除hexo-feed用到的模板文件
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

autoprefixer:
  exclude:
    - '*.min.css'
## live2d
live2d:
  enable: true # 是否开启live2d
  scriptFrom: local # 脚本从本地引入
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
      use: live2d-widget-model-koharu # 填写放进live2d_models文件夹中的模型文件夹名字
      scale: 1 # canvas 模型与canvas的缩放
  display:
      width: 150 # 宽度
      height: 300 # 高度
      position: right # 显示位置
      hOffset: 0 #水平偏移
      vOffset: -20 #垂直偏移
  mobile:
      show: true # 手机端是否显示
      scale: 0.5 # 移动设备上的缩放
  react:
    opacity: 0.7 # 透明度
  dialog: 
    enable: true
    text:
      - 汉室衰微，朝纲霍乱
      - 你在狗叫什么

baidu_url_submit: 
  count: 100 ## 比如100，代表提交最新的一百个链接 
  host: guoyanjun.top ## 在百度站长平台中注册的域名 
  token: your_token ## 刚刚复制的秘钥，不要公布到任何地方。 
  path: baidu_urls.txt ## 文本文档的地址，新链接会保存在此文本文档里
